---
  - name: Install Kubectl
    tags:
      - kubernetes
    homebrew:
      name: kubernetes-cli,kubernetes-helm
      state: present

  - name: Install OpenLens
    tags:
      - kubernetes
    homebrew_cask:
      name: openlens
      state: present

  - name: Check for existing ~/.zshrc
    tags:
      - kubernetes
      - zsh
    stat:
      path: "{{ansible_env.HOME}}/.zshrc"
    register: zshrc

  - name: Add kubectl ZSH plugin
    tags:
      - kubernetes
      - zsh
    replace:
      path: "{{ansible_env.HOME}}/.zshrc"
      regexp: ^plugins=\((.*)\)
      replace: plugins=(\1 kubectl)
    when: zshrc.stat.exists == true

  - name: Add Helm ZSH plugin
    tags:
      - kubernetes
      - zsh
    replace:
      path: "{{ansible_env.HOME}}/.zshrc"
      regexp: ^plugins=\((.*)\)
      replace: plugins=(\1 helm)
    when: zshrc.stat.exists == true
